CSLI PDD
RIT-Space-Exploration/SPEX-Standard-Proposal pull request #35
Opened 2018-08-10 17:23 UTC by jprks

### Authors
tag authors here, including their github username 
* James Parkus @jprks
* Austin Bodzas @Beaudidly 

### Abstract
The purpose of this project is to go through the design stages of the CSLI\@. The team will choose a scientific payload, engineer the CubeSat to house and function the payload, begin writing the CSLI by excluding the funding section, and perform a full cost estimation. This stage will leave off with a firm idea of the road ahead for funding and fabrication. The next stage will start with funding based off the cost estimations this team makes.

2018-08-11 04:14 UTC, runphilrun reviewed
will read later

2018-08-11 04:14 UTC, runphilrun commented on CSLI/sample-formats.bib
> +@article{article,
delete this file

2018-08-11 04:14 UTC, runphilrun commented on CSLI/sample-with-examples.bib
> +@manual{lamp87,
delete this file

2018-08-11 04:14 UTC, runphilrun commented on CSLI/CSLI.tex
> +\title{CubeSat Launch Initiative Phase I\@: \newline Design \& Research}
use `\\` instead of `\newline`

2018-08-11 04:14 UTC, runphilrun commented on CSLI/CSLI.tex
> +The long-term vision of this project is to launch a CubeSat. This project begins with the most important phase, the initial design and research. Once this is complete the team will move onto
You say that this is Phase 1, but you don't define Phases 2+. Define the future phases in this section leading up to a flight-ready cubesat ready for orbit.

2018-08-11 04:14 UTC, runphilrun commented on CSLI/CSLI.tex
> +This part of the project, Phase I, will concern itself with the design and research of the CubeSat. This spans everything from picking/researching a payload
picking/researching --> choosing

2018-08-11 04:24 UTC, venku122 requested changes
CSLI/SPEXpdd.pdf
CSLI/figs/project-life-cycle.png
CSLI/figs/project life cycle.vsdx
CSLI/SPEXpdd.pdf

Can be removed.

Overall, I think the project definition is too vague. Activities should be clarified and well-defined, so successful completion of those activities can be measured.

2018-08-11 04:24 UTC, venku122 commented on CSLI/sample-formats.bib
> +@article{article,
This can be removed

2018-08-11 04:24 UTC, venku122 commented on CSLI/sample-with-examples.bib
> +@manual{lamp87,
This can be removed.

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +The purpose of this project is to go through the design stages of the CSLI\@. The team will choose a scientific payload, engineer the CubeSat to house and function
What does 'engineer' mean in this context. Overall, I am a bit confused reading this PDD. Is this a[ Pre-Phase A/Phase A](https://nodis3.gsfc.nasa.gov/policy_letters/NM_7120-81_.pdf) research project, or is actual system and subsystem design occurring? CAD and electrical engineering skills are referenced later in the document which leads me to believe the latter. Is that correct?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +the payload, begin writing the CSLI by excluding the funding section, and perform a full cost estimation. This stage will leave off with a firm idea of the road ahead for funding and fabrication. The
Again, a bit of confusion here, as 'writing the CSLI' I believe references the grant proposal document, while other sections of this PDD focus on engineering design and development. What exactly will be done at the end of this project? High-level CAD models, sub-assemblies, PCB designs?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +\IEEEPARstart{T}{he} CubeSat Launch Initiative will be a great opportunity for RIT SPEX members to use their technical skills to make an electromechanical system.
Some more context on the CSLI proposal process including specific details and timelines would be appreciated. The text relies on a lot of extra context to be properly understood. Imagine showing this to an RIT professor, who had never heard of the CSLI program, but might be interested in flying a payload or mentoring the team. What would you need to tell them to get them on the same page?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +to design, fabricate, and launch RIT's first CubeSat. There are several phases to this mission and will not be restricted to a tight-timeline. The team will be given ample
As I mentioned before, references to 'engineer' 'design' 'fabricate' and 'launch' are used throughout. What specific activities are planned for this project? Consider moving 'CSLI Part 2-N' activities to the long-term vision section to indicate they are follow-on projects.

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +This part of the project, Phase I, will concern itself with the design and research of the CubeSat. This spans everything from picking/researching a payload
How will payloads be researched? What activities will be performed to learn more about payload ideas? What does the selection process look like?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +to designing the integration of that payload to the CubeSat, with all the features required by the CSLI\@. The primary objective of this phase is to create a
For payload integration, to what level is the rest of the cubesat developed? Is each major subsystem designed? Will subsystems be purchased Commercial Off The Shelf (COTS) or developed in-house? What features are required by the CSLI? How is integration defined? Does that include the mechanical mounting of payload hardware within the cubesat? Are wiring and power diagrams required? Will thermal management analysis of the whole cubesat or just the payload subsystem be performed?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +fully developed CAD model, which includes a fully researched and developed scientific payload, and the proper documentation concerned with the electronic features such that the team can write a fully
What defines a fully researched and developed scientific payload? Will the physical payload hardware be developed and tested? 

What documentation of electronic features is expected? Is that wiring diagrams or board layouts? Does that concern power distribution or data handling? Does it cover software? Is the electronic work scoped to just the electronics for the payload or also the whole cubesat?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +for data analytics on collected data, PR, provides base for further funding and sponserships.
Can you describe what data will be collected? Will there be physical demonstrations or prototypes or will data be generated via simulations? What data processing do you expect to do? What variables are being measured and collected?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +The PR for this would be great for getting recognition in the aerospace community. A successful CubeSat is
I am still a bit confused. Does this project result in a finished cubesat? The wording here implies the PR benefits come with a successful cubesat flight? What are the immediate PR benefits of the work described in this project?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +and grow in their research. The experience for the team would be great because it would bring a project from pure design and research to flight. Allowing students
Again, it seems like this describes actual construction of a flight ready cubesat rather than scientific payload exploration studies.

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +software and firmware development, etc. The team will be responsible for creating thorough documentation on every aspect of the CubeSat to ensure future members will be able to pick it up and
Will firmware be written for this project? Will they use development board or other hardware?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +This project will start with a small design and research team. That team will be responsible for picking and appropriate payload. Once the payload is chosen, the
>~and~ an

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +software and firmware development, etc. The team will be responsible for creating thorough documentation on every aspect of the CubeSat to ensure future members will be able to pick it up and
What kind of documentation is intended here? Are these assembly/manufacturing instructions or just notes on decisions and other research activities?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +    1 & Define mission needs \\
Nice to see these steps listed out. 

It would be nice to see more detail on how these steps apply to the project, and what will actually be done during each step. Tangible deliverables can help the team stay focused.

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +The team will make 2 or 3 postings on the RIT SPEX website, per semester, with progress and science updates to keep the project in outside contributors/persons of
Nice 👍

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +to have enough documentation on each aspect to be able to bring new members up-to-speed as easy and quick as possible. The documentation should cover the following; fully end-to-end CubeSat assembly,
What defines enough? What specific topics will be covered and in what way? Is it meeting notes and powerpoints or official reports that cover topics in-depth?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +This phase of the project will be considered complete when the following is delivered; a fully developed CAD model, electrical diagrams describing the electrical functionality,
What specific electrical diagrams/PCBs are planned to be designed? Does it include the science board or all PCBs within the cubesat?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +Once these first milestones are completed the team will go through a concept design review. This will give them early feedback based on their design decisions and
👍

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +designing the payload, CubeSat structure, CubeSat avionics and software. Then also creating a risk assessment based on the first design iteration.
Does this cover designing the software or writing software?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +Preparation for funding will include making many documents and graphics to show the project to potential investors and or to please already dedicated investors.
What specific documents do you plan to produce? Is this another sponsorship packet, resources for a kickstarter/crowdfunding campaign, or something else? What potential investors are considered? Is this a commercial product?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +In general, it is expected that mechanical engineers will be profficient in Solidworks and MATLAB. Solidworks is the chosen 3D modeling software due wide availability and experience.
>~due~ due to

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +MATLAB will be used for calculating orbits or performing mechanical analysis. It is not required for people that have a refined coding ability. Mechanical engineers will need to
Orbit calculations would be very interesting. It would be nice to see that defined as an objective or deliverable.

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +The funding requirements for this design phase are minimal. There may be some cost during feasability studies if a particular technology must be demonstrated.
What specific technology demonstrators would be built?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +Faculty support is difficult to gauge based on the ambiguity of the payload. Since the payload is completely unknown at this time, the extent of faculty support will be considered when
Will faculty support be sought out during the payload exploration phase?

2018-08-11 04:24 UTC, venku122 commented on CSLI/CSLI.tex
> +The author would like to thank Dr.~Bill Destler and Rebecca Johnson for being exemplary humans, Anthony Hennig for founding RIT Space Exploration, and all the SPEX members that continue to invest the
This section should be customized to be directly applicable or removed.

2018-08-11 06:38 UTC, runphilrun reviewed
I read through previous comments from other users and agree with pretty much all of them. It's not clear to me if the deliverable is intended to be a white paper, a paper entry to a competition, or flight-ready hardware? What will the cubesat do?

2018-08-11 06:38 UTC, runphilrun commented on CSLI/CSLI.tex
> +The purpose of this project is to go through the design stages of the CSLI\@. The team will choose a scientific payload, engineer the CubeSat to house and function
CSLI is usually a means to an end, like how USIP was an avenue to do CSTARS. Is this paper outlining why SPEX should design _something_ for CSLI or outlining a specific project (or family of projects) that make use of CSLI to meet their goals?

2018-08-11 06:38 UTC, runphilrun commented on CSLI/CSLI.tex
> +to design, fabricate, and launch RIT's first CubeSat. There are several phases to this mission and will not be restricted to a tight-timeline. The team will be given ample
"this mission" hasn't been described yet beyond a cubesat following the CSLI rules/SOP. can you describe some goals for the scientific objective?

2018-08-11 06:38 UTC, runphilrun commented on CSLI/CSLI.tex
> +The PR for this would be great for getting recognition in the aerospace community. A successful CubeSat is
+1 to above questions

2018-08-12 20:18 UTC, jprks commented on CSLI/CSLI.tex
> +Faculty support is difficult to gauge based on the ambiguity of the payload. Since the payload is completely unknown at this time, the extent of faculty support will be considered when
No, we will find them when we choose the payload.

2018-08-12 20:22 UTC, jprks commented on CSLI/CSLI.tex
> +The funding requirements for this design phase are minimal. There may be some cost during feasability studies if a particular technology must be demonstrated.
Unknown at this time. It completely depends on the selected payload.

2018-08-13 01:05 UTC, venku122 commented
@jprks No PDD needs to be deleted if its not immediately approved. The PR can be merged and its a great starting point for future projects.

2018-10-13 19:35 UTC, merged